name: Pages
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Install locales
      run: |
        sudo apt-get install --yes locales-all --reinstall

    - name: Download template
      run: |
        git clone https://github.com/GISMentors/sphinx-template.git $RUNNER_WORKSPACE/sphinx-template

    - name: Build and Commit
      uses: sphinx-notes/pages@2.1
      with:
        documentation_path: ./
        sphinx_version: 5.3.0
          
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
